# Generated by Django 3.1.1 on 2020-09-23 23:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20200924_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved_cooment',
            new_name='approved_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 23, 19, 52, 687672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 23, 19, 52, 687672, tzinfo=utc)),
        ),
    ]
